Repository it-e-7/Algorithm, pull requests merged in 2023-08, with the labels that each got.

#1024 [Programmers] 23-07-31
  Programmers/완전탐색/전력망을둘로나누기_홍석현.py
  Programmers/완전탐색/피로도_홍석현.py
Labels: 홍석현

#1022 [Programmers] 23-07-31
  Programmers/완전탐색/전력망을둘로나누기_김승주.py
  Programmers/완전탐색/카펫_김승주.py
  Programmers/완전탐색/피로도_김승주.py
Labels: 김승주

#1021 [Programmers] 23-07-31
  Programmers/완전탐색/모음사전_노유민.py
Labels: 노유민

#1020 [Programmers] 23-07-31
  Programmers/완전탐색/모음사전_조상원.py
  Programmers/완전탐색/모의고사_조상원.py
  Programmers/완전탐색/소수찾기_조상원.py
  Programmers/완전탐색/전력망을둘로나누기_조상원.py
  Programmers/완전탐색/최소직사각형_조상원.py
  Programmers/완전탐색/카펫_조상원.py
  Programmers/완전탐색/피로도_조상원.py
Labels: 조상원

#1026 [Programmers] 23-07-31
  Programmers/완전탐색/모음사전_박보선.py
  Programmers/완전탐색/모의고사_박보선.py
  Programmers/완전탐색/소수찾기_박보선.py
  Programmers/완전탐색/최소직사각형_박보선.py
  Programmers/완전탐색/카펫_박보선.py
  Programmers/완전탐색/피로도_박보선.py
Labels: 박보선

#1027 [Programmers] 23-08-01
  Programmers/완전탐색/모음사전_장서윤.py
  Programmers/완전탐색/소수찾기_장서윤.py
  Programmers/완전탐색/전력망을둘로나누기_장서윤.py
  Programmers/완전탐색/카펫_장서윤.py
  Programmers/완전탐색/피로도_장서윤.py
Labels: 장서윤

#1025 [Programmers] 23-08-01
  Programmers/탐욕법/체육복_노유민.py
Labels: 노유민

#1028 [Programmers] 23-08-02
  Programmers/탐욕법/조이스틱_노유민.py
Labels: 노유민

#1030 [Programmers] 23-08-03
  Programmers/탐욕법/구명보트_장서윤.py
  Programmers/탐욕법/체육복_장서윤.py
  Programmers/탐욕법/큰수만들기_장서윤.py
Labels: 장서윤

#1029 [Programmers] 23-08-03
  Programmers/탐욕법/큰수만들기_노유민.py
Labels: 노유민

#1032 [Programmers] 23-08-04
  Programmers/탐욕법/구명보트_김설희.py
  Programmers/탐욕법/단속카메라_김설희.py
  Programmers/탐욕법/섬연결하기_김설희.py
  Programmers/탐욕법/조이스틱_김설희.py
  Programmers/탐욕법/체육복_김설희.py
  Programmers/탐욕법/큰수만들기_김설희.py
Labels: 김설희

#1031 [Programmers] 23-08-04
  Programmers/탐욕법/구명보트_노유민.py
Labels: 노유민

#1034 [Programmers] 23-08-06
  Programmers/DFS_BFS/게임맵최단거리_김설희.py
  Programmers/동적계획법/정수삼각형_김설희.py
Labels: 김설희

#1033 [Programmers] 23-08-06
  Programmers/탐욕법/섬연결하기_노유민.py
Labels: 노유민

#1038 [Programmers] 23-08-07
  Programmers/탐욕법/구명보트_최승열.py
  Programmers/탐욕법/단속카메라_최승열.py
  Programmers/탐욕법/섬연결하기_최승열.py
  Programmers/탐욕법/조이스틱_최승열.py
  Programmers/탐욕법/체육복_최승열.py
  Programmers/탐욕법/큰수만들기_최승열.py
Labels: 최승열

#1037 [Programmers] 23-08-07
  Programmers/탐욕법/구명보트_홍석현.py
  Programmers/탐욕법/조이스틱_홍석현.py
  Programmers/탐욕법/체육복_홍석현.py
  Programmers/탐욕법/큰수만들기_홍석현.py
Labels: 홍석현

#1036 [Programmers] 23-08-07
  Programmers/탐욕법/단속카메라_노유민.py
Labels: 노유민

#1035 [Programmers] 23-08-07
  Programmers/탐욕법/구명보트_조상원.py
  Programmers/탐욕법/단속카메라_조상원.py
  Programmers/탐욕법/섬연결하기_조상원.py
  Programmers/탐욕법/조이스틱_조상원.py
  Programmers/탐욕법/체육복_조상원.py
  Programmers/탐욕법/큰수만들기_조상원.py
Labels: 조상원

#1039 [Programmers] 23-08-07
  Programmers/탐욕법/단속카메라_장서윤.py
  Programmers/탐욕법/섬연결하기_장서윤.py
  Programmers/탐욕법/조이스틱_장서윤.py
Labels: 장서윤

#1040 [Programmers] 23-08-09
  Programmers/동적계획법/N으로표현_노유민.py
Labels: 노유민

#1043 [Programmers] 23-08-12
  Programmers/동적계획법/도둑질_장서윤.py
  Programmers/동적계획법/등굣길_장서윤.py
  Programmers/동적계획법/정수삼각형_장서윤.py
Labels: 장서윤

#1044 [Programmers] 23-08-13
  Programmers/동적계획법/도둑질_노유민.py
  Programmers/동적계획법/등굣길_노유민.py
  Programmers/동적계획법/사칙연산_노유민.py
  Programmers/동적계획법/정수삼각형_노유민.py
Labels: 노유민

#1047 [Programmers] 23-08-22
  Programmers/동적계획법/도둑질_최승열.py
  Programmers/동적계획법/정수삼각형_최승열.py
Labels: 최승열

#1041 [Programmers] 23-08-11
  Programmers/동적계획법/N으로표현_송민진.py
  Programmers/동적계획법/등굣길_송민진.py
  Programmers/동적계획법/정수삼각형_송민진.py
Labels: 송민진

#1046 [Programmers] 23-08-22
  Programmers/동적계획법/정수삼각형_김승주.py
Labels: 김승주

#1042 [Programmers] 23-08-11
  Programmers/동적계획법/등굣길_김설희.py
Labels: 김설희

#1045 [Programmers] 23-08-21
  Programmers/동적계획법/등굣길_홍석현.py
  Programmers/동적계획법/정수삼각형_홍석현.py
  Programmers/정렬/HIndex_홍석현.py
Labels: 홍석현
